### ISSUE TITLE
Questions about processing delays

### ISSUE THREAD

**Issue by wjcyun** [snehitvaddi/FaceMask-Detection-using-Deeplearning#4]
Hello: 
  My recent work is to detect moving objects in video and do a closed-loop processing, so I'd like to ask how much processing latency there will be for real-time processing of video streams, such as detecting faces, or what kind of computer configuration is needed to make the latency as small as possible？ Looking forward to your answer.Thank you!

**Comment by snehitvaddi** [comment]
From my knowledge there are few ways to get better results with low latency like reducing model size (use lightweight models like yolo* lite), feature reduction(use image processing steps to eliminate unwanted stuff), batch wise processing(Instead of inferencing each and every frame, use optimized pipelines like queue to processes after n frames).

Please feel free to correct me if I'm wrong in something and also ask questions if you have any😊

**Comment by wjcyun** [comment]
Thank you so much for your reply, it was very helpful to me.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "snehitvaddi/FaceMask-Detection-using-Deeplearning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月17日(星期五) 中午1:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [snehitvaddi/FaceMask-Detection-using-Deeplearning] Questions about processing delays (Issue #4)





 
From my knowledge there are few ways to get better results with low latency like reducing model size (use lightweight models like yolo* lite), feature reduction(use image processing steps to eliminate unwanted stuff), batch wise processing(Instead of inferencing each and every frame, use optimized pipelines like queue to processes after n frames).
 
Please feel free to correct me if I'm wrong in something and also ask questions if you have any😊
